### ISSUE TITLE
Incorrect Caldroid fragment height in ScrollView

### ISSUE THREAD

**Issue by gabororosz** [roomorama/Caldroid#53]
Hi,

Tried to reproduce Roomorama's nice Availability page, with multiple, scrollable Caldroid fragments:
https://www.dropbox.com/s/0kpb8435ffv1psp/Screenshot_2013-08-26-18-17-53.png

If I add multiple Caldroid fragments to a LinearLayout that's fine, no problem at all. BUT if I embed it into a ScrollView, height will be messed, and I'll get this:
https://www.dropbox.com/s/g3ntnkrnr8shbbv/Screenshot_2013-08-26-17-57-54.png

Please let me know if you have any idea, or workaround.

Thank you!

**Comment by mielet** [comment]
I believe I may have found a better solution to the vertical sizing on a scrollView, I believe by programatically changing the calendar's height by having it scaled to the current device's height there wouldn't be a need for multiple layouts. Something like this has given me luck.

LinearLayout linearCalendar = (LinearLayout)findViewById(R.id.calendarView);

        Display display = getWindowManager().getDefaultDisplay();
        Point size = new Point();
        display.getSize(size);

        // Storing the screen height into an int variable
        int height = size.y;
        int width = size.x;

        // Retrieves the current parameters of the layout and storing them in variable params

        ViewGroup.LayoutParams params = linearCalendar.getLayoutParams();

        // Re-setting the height parameter to .51 the max screen height

        params.height =  (int)Math.round(height*.51);
        params.width = (int)Math.round(width*.80);

Note that these are the scalings for my calendar only taking up 80% of my screen width, I believe that if you have the calendar's width as "match_parent" you need to use ~62% for the screen height.

**Comment by grennis** [comment]
Digging around a bit, the root of the issue is that GridView is being used to render the calendar (see https://github.com/roomorama/Caldroid/blob/master/caldroid/src/main/res/layout/calendar_view.xml)

GridView is notorious for not being able to wrap its height correctly. However, I have used workarounds in the past for it and I verified it does work here. Without using math to try to guesstimate the height.

First in your layout give it a height thats way too much:
```
			<FrameLayout android:id="@+id/calendar_container"
				android:layout_width="match_parent"
				android:layout_height="999dp" />
```
Then in onCreate, after creating the fragment and adding it, set a layout listener:
```
calendarContainer.getViewTreeObserver().addOnGlobalLayoutListener(CalendarViewTreeObserver);
```
Where your observer looks like this:
```
	private ViewTreeObserver.OnGlobalLayoutListener CalendarViewTreeObserver = new ViewTreeObserver.OnGlobalLayoutListener() {
		@Override
		public void onGlobalLayout() {
			calendarContainer.getViewTreeObserver().removeOnGlobalLayoutListener(CalendarViewTreeObserver);
			ViewGroup.MarginLayoutParams lp = (ViewGroup.MarginLayoutParams) calendarContainer.getLayoutParams();
			lp.height = ((ViewGroup)calendarContainer).getChildAt(0).getHeight();
			calendarContainer.setLayoutParams(lp);
			calendarContainer.requestLayout();
		}
	};
```
Now, the calendar can measure itself and the container will set it's height automatically. Works on all phone sizes and orientations.

**Comment by thomasdao** [comment]
Hi all, finally I have fixed this issue in latest Caldroid 2.3.0, let me know if it works, thanks

**Comment by grennis** [comment]
Yes, it works. I was able to remove my hack to work around it. Thanks!

**Comment by thomasdao** [comment]
@grennis thanks for help testing it :+1:

**Comment by AdelineJolie** [comment]
Excellent, thanks grennis for helping to fix this and thomasdao for this awesome lib.

**Comment by engr-erum** [comment]
@thomasdao  i m using caldroid 2.3.0 but it still showing a little bit 80% of device height in some device while i have set 300dp framelayout height in xml also set this but nothing works for Huwaei device 
    <FrameLayout
                android:id="@+id/flayout_calendar"
                android:layout_width="match_parent"
                android:layout_height="250dp"
                android:layout_below="@+id/txt_selectdelivery" />
private ViewTreeObserver.OnGlobalLayoutListener CalendarViewTreeObserver = new ViewTreeObserver.OnGlobalLayoutListener() {
        @Override
        public void onGlobalLayout() {
            calendarContainer.getViewTreeObserver().removeOnGlobalLayoutListener(CalendarViewTreeObserver);
            ViewGroup.MarginLayoutParams lp = (ViewGroup.MarginLayoutParams) calendarContainer.getLayoutParams();
            lp.height = ((ViewGroup)calendarContainer).getChildAt(0).getHeight();
            calendarContainer.setLayoutParams(lp);
            calendarContainer.requestLayout();
        }
    };
